version: "3"

services:
  nextcloud-db:
    image: mariadb:10.6
    container_name: nextcloud-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    ports:
      - "127.0.0.1:3308:3306"
    volumes:
      - ./nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    env_file:
      - .env

  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud-app
    restart: always
    network_mode: host
    volumes:
      - ./nextcloud-data:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=127.0.0.1
      - MYSQL_TCP_PORT=3308
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_DOMAIN}
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=${NEXTCLOUD_DOMAIN}
      - OVERWRITEWEBROOT=/nextcloud
      - OVERWRITECLIURL=https://${NEXTCLOUD_DOMAIN}/nextcloud
    env_file:
      - .env
    command: sh -c "sed -i 's/Listen 80/Listen 9977/g' /etc/apache2/ports.conf && sed -i 's/:80/:9977/g' /etc/apache2/sites-available/000-default.conf && apache2-foreground"
